### PR TITLE
Fix charity dialog

### LINKED ISSUE #279: Make campaign charity dialog the same size

### LINKED ISSUE #280: Campaign charity dialog CLOSE button needs to be more obvious, the location is a bit weird too

### PR DESCRIPTION
**Pull request by sivayogasubramanian**
Closes #280 
Closes #279

### CODE REVIEW

File: frontend/components/campaigns/campaignCharities/CampaignCharityDialog.tsx [hunk 1]
```diff
@@ -49,19 +55,15 @@ const CampaignCharityDialog = ({ campaignCharity, open, handleClose }: Props) =>
...
 
-      <DialogActions sx={dialogActionsSx}>
+      <DialogActions>
         <Button
-          actionType="mutedWithoutOutline"
-          size="small"
+          actionType="secondary"
+          fullWidth
           startIcon={<LinkIcon />}
           onClick={() => router.push(campaignCharity.charity.websiteUrl)}
```
Comment (zognin) [inline frontend/components/campaigns/campaignCharities/CampaignCharityDialog.tsx:63]: is it possible for the charity website to open in a new tab?

File: frontend/styles/components/charities/CampaignCharityDialogStyles.ts [hunk 2]
```diff
@@ -1,5 +1,14 @@
 import { SxProps } from '@mui/material';
 
+export const dialogSx: SxProps = {
```
Comment (zognin) [inline frontend/styles/components/charities/CampaignCharityDialogStyles.ts:3]: Does `<Dialog PaperProps={{sx: sthSx}} ... />` work? I've tried it before

https://stackoverflow.com/questions/50649408/how-to-use-material-ui-dialog-paperprops

**Review by zognin — COMMENTED** [review]
Screenshot 2022-10-24 at 12 17 24 AM


Is it possible to be able to see everything without requiring scrolling?

edit: wrong pic oops

**Review by zognin — APPROVED** [review]
LGTM thanks, nit: can the dialog width scale? 
photo_2022-10-24 20 46 59
