### PR TITLE
Fix charity dialog

### LINKED ISSUE #302: Image scaling of CharityDialog

### PR DESCRIPTION
**Pull request by sivayogasubramanian**
Closes #302 

Also improved RedirectDialog message

### CODE REVIEW

File: frontend/components/redeem/RedirectDialog.tsx [hunk 1]
```diff
@@ -114,7 +140,13 @@ const RedirectDialog = ({
                     )}
                   </Stack>
 
-                  <Button type="submit" actionType="primary" startIcon={<LockIcon />} fullWidth>
+                  <Button
+                    type="submit"
+                    disabled={!values.hasAcknowledged}
```
Comment (zognin) [inline frontend/components/redeem/RedirectDialog.tsx:145]:
```suggestion
                    disabled={!isValid || !dirty}
```

**Review by zognin — APPROVED** [review]
LGTM, one comment
