### PR TITLE
Fix campaign charity not saving edits.

### LINKED ISSUE #200: Edit campaign doesn't update new charity link

### PR DESCRIPTION
**Pull request by bharathcs**
Fixes #200

### CODE REVIEW

File: backend/app/controllers/campaigns_controller.rb [hunk 1]
```diff
@@ -103,6 +103,7 @@ def create_or_update_campaign_charities
       campaign_charity = CampaignCharity.find_or_initialize_by(id: param[:id])
       campaign_charity.giving_sg_url = param[:giving_sg_url]
       campaign_charity.charity_id = param[:charity][:id]
+      campaign_charity.save!
```
Comment (ganhongyao) [inline backend/app/controllers/campaigns_controller.rb:106]: Let's not do `save!` here since we already do so on line 48, to make sure that the changes are atomic. 

Can we do the assignment to `@campaign.campaign_charities` on line 102 instead?

**Review by ganhongyao — APPROVED** [review]
Thanks for helping to fix! Let me know if the proposed change does not work, else can merge after the change.

File: backend/app/controllers/campaigns_controller.rb (hunk 1 above)
Comment (bharathcs) [reply backend/app/controllers/campaigns_controller.rb:106]: Resolved offline.
